import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../styles/globals.css'

const inter = Inter({ subsets: ["latin"] });

//ชื่อเว็บ+คำอธิบาย
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//เลย์เอาท์ทุกหน้า คล้ายๆ router
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
